PREFIX rel: <http://www.perceive.net/schemas/relationship/> 
PREFIX type: <http://www.perceive.net/schemas/type/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 


SELECT ?who ?alive
WHERE {
    ?who a type:Noble .
    ?who foaf:isAlive ?alive .
}